language: cpp
compiler: 
    - clang
notifications:
    email: true
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/julianightlies -y
    - sudo apt-get update -qq -y
    - sudo apt-get install libpcre3-dev julia -y
    - git config --global user.name "Travis User"
    - git config --global user.email "travis@example.net"
script:
    - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("ChainedVectors"))`); Pkg.pin("ChainedVectors"); Pkg.resolve()'
    - julia -e 'using ChainedVectors; @assert isdefined(:ChainedVectors); @assert typeof(ChainedVectors) === Module'
    - julia ./test/tests.jl
